#!/usr/bin/env python3
# Generate thin runtime adapters from the canonical RAD .rad/ definition.
# No third-party dependencies. Python 3.9+.

from pathlib import Path
import argparse, hashlib, json, sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = json.loads((ROOT/'.rad/manifest.json').read_text(encoding='utf-8'))
ROLES = MANIFEST['roles']
CORE = MANIFEST['core_protocol']
ORCH = MANIFEST['orchestrator_role']
POLICIES = MANIFEST['policies']

DESCRIPTIONS = {
 'frontend-dev':'Frontend implementation specialist. Use for user-facing/client implementation and frontend unit tests.',
 'backend-dev':'Backend/domain specialist. Use for domain logic, APIs, persistence, providers and backend/domain tests.',
 'qa':'Independent RAD QA. Use after implementation to author/run E2E validation, manage DEFECTS.md and independently retest fixes.',
 'adversary':'Adversarial RAD reviewer. Use after QA/implementation to attack edge cases and record findings without fixing them.',
}

def normalized_bytes(path):
    # Stable core hashes across CRLF/LF checkouts.
    data=(ROOT/path).read_bytes()
    return data.replace(b'\r\n', b'\n').replace(b'\r', b'\n')

def digest(paths):
    h=hashlib.sha256()
    for p in paths:
        h.update(p.encode()); h.update(b'\0'); h.update(normalized_bytes(p)); h.update(b'\0')
    return h.hexdigest()[:16]

CANON = [CORE, ORCH] + [v['path'] for v in ROLES.values()] + POLICIES + list(MANIFEST['workflows'].values())
CORE_HASH=digest(CANON)

SAFE_BASH = '''  bash:
    "*": ask
    "git status*": allow
    "git diff*": allow
    "git log*": allow
    "git show*": allow
    "python tools/generate_adapters.py --check*": allow
    "python ./tools/generate_adapters.py --check*": allow
    "python3 tools/generate_adapters.py --check*": allow
    "npm test*": allow
    "npm run test*": allow
    "npm run build*": allow
    "npm run lint*": allow
    "npx playwright test*": allow
'''

def bridge(role):
    rp=ROLES[role]['path']
    return f'''This is a generated RAD runtime adapter.

Before doing any work, read `{CORE}` and `{rp}`. Read the relevant workflow under `.rad/workflows/` and applicable policies under `.rad/policies/`. Those canonical files are the source of truth. `REQUIREMENTS.md` is immutable. If this adapter conflicts with `.rad/`, follow `.rad/`.
'''

def header(prefix='#'):
    return f"{prefix} GENERATED BY RAD 3 adapter generator — DO NOT HAND EDIT — core {CORE_HASH}\n"

def md_comment():
    return f"<!-- GENERATED BY RAD 3 adapter generator — DO NOT HAND EDIT — core {CORE_HASH} -->\n"

def codex():
    out={}
    out['.codex/config.toml'] = header('#') + '''model = "gpt-5.6-sol"
model_reasoning_effort = "high"
approval_policy = "on-request"
default_permissions = ":workspace"

[windows]
sandbox = "elevated"

[agents]
max_concurrent_threads_per_session = 4
default_subagent_model = "gpt-5.6-sol"
default_subagent_reasoning_effort = "high"
'''
    for r in ROLES:
        effort='xhigh' if r=='adversary' else 'high'
        body=bridge(r).replace(chr(34)*3,'')
        q=chr(34)*3
        out[f'.codex/agents/{r}.toml'] = header('#') + f'''name = "{r}"
description = "{DESCRIPTIONS[r]}"
model = "gpt-5.6-sol"
model_reasoning_effort = "{effort}"

developer_instructions = {q}
{body}
{q}
'''
    out['.codex/README.md']=header('#')+'''# Codex adapter

The main Codex thread is the RAD orchestrator through root `AGENTS.md`.
Delegated roles are generated under `.codex/agents/`.
'''
    return out

def opencode():
    out={}
    orch='''---
description: RAD delivery lead. Plans, delegates, triages and gates; never writes product code.
mode: primary
permission:
  edit:
    "*": deny
    "DEFECTS.md": allow
    "ADVERSARIAL_REVIEW.md": allow
    "POC_REPORT.md": allow
    "DECISIONS.md": allow
    "NAMING_AUDIT.md": allow
    "docs/adr/*": allow
'''+SAFE_BASH+'''---

'''
    out['.opencode/agents/orchestrator.md']=orch+md_comment()+f'Read `{CORE}` and `{ORCH}`. Those files are canonical. Read the relevant `.rad/workflows/` and `.rad/policies/` files before each gate.\n'
    for r in ROLES:
        if r in ('frontend-dev','backend-dev'):
            perm='''permission:
  edit:
    "*": allow
    "REQUIREMENTS.md": deny
    ".rad/*": deny
    ".codex/*": deny
    ".opencode/*": deny
    ".claude/*": deny
    ".cursor/*": deny
    "DEFECTS.md": deny
    "ADVERSARIAL_REVIEW.md": deny
    "e2e/*": deny
'''+SAFE_BASH
        elif r=='qa':
            perm='''permission:
  edit:
    "*": deny
    "e2e/*": allow
    "screenshots/evidence/*": allow
    "screenshots/generated/*": allow
    "DEFECTS.md": allow
    "NAMING_AUDIT.md": allow
'''+SAFE_BASH
        else:
            perm='''permission:
  edit:
    "*": deny
    "ADVERSARIAL_REVIEW.md": allow
    "screenshots/evidence/*": allow
    "screenshots/generated/*": allow
'''+SAFE_BASH
        fm=f'''---
description: {DESCRIPTIONS[r]}
mode: subagent
{perm}---

'''
        out[f'.opencode/agents/{r}.md']=fm+md_comment()+bridge(r)
    out['.opencode/README.md']=header('#')+'''# OpenCode adapter

Select the generated `orchestrator` primary agent. It delegates to the four generated subagents. OpenCode-specific permissions strengthen canonical role ownership while allowing routine local validation commands; package installation/network-sensitive commands still require approval.
'''
    return out

def claude():
    out={}
    out['CLAUDE.md']=md_comment()+'@AGENTS.md\n\nThe canonical RAD instructions are under `.rad/`. Treat generated `.claude/` files as adapters only.\n'
    for r in ROLES:
        fm=f'''---
name: {r}
description: {DESCRIPTIONS[r]}
model: inherit
---

'''
        out[f'.claude/agents/{r}.md']=fm+md_comment()+bridge(r)
    out['.claude/README.md']=header('#')+'''# Claude Code adapter

Root `CLAUDE.md` imports the shared `AGENTS.md`. Custom delegated roles live in `.claude/agents/`. The main Claude session acts as orchestrator.
'''
    return out

def cursor():
    out={}
    for r in ROLES:
        fm=f'''---
name: {r}
description: {DESCRIPTIONS[r]}
---

'''
        out[f'.cursor/agents/{r}.md']=fm+md_comment()+bridge(r)
    commands={
      'rad-preflight.md':'.rad/workflows/preflight.md',
      'rad-audit.md':'.rad/workflows/architecture-audit.md',
      'rad-build.md':'.rad/workflows/implementation.md',
      'rad-resume.md':'.rad/workflows/resume.md',
      'rad-release.md':'.rad/workflows/final-release.md'
    }
    for fn,path in commands.items():
        out[f'.cursor/commands/{fn}']=md_comment()+f'Read `{path}` and execute that canonical RAD workflow. Also follow root `AGENTS.md` and `.rad/core/protocol.md`.\n'
    out['.cursor/README.md']=header('#')+'''# Cursor adapter

Cursor reads root `AGENTS.md`. Native RAD delegated roles live in `.cursor/agents/`; convenience commands live in `.cursor/commands/`. The main Cursor Agent acts as orchestrator.
'''
    return out

GENERATORS={'codex':codex,'opencode':opencode,'claude':claude,'cursor':cursor}

def expected(selected):
    e={}
    for r in selected: e.update(GENERATORS[r]())
    return e

def write_files(files):
    for rel,text in files.items():
        p=ROOT/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')

def check_files(files):
    bad=[]
    for rel,text in files.items():
        p=ROOT/rel
        if not p.exists() or p.read_text(encoding='utf-8')!=text: bad.append(rel)
    return bad

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--runtime', choices=list(GENERATORS), action='append')
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--check', action='store_true')
    args=ap.parse_args()
    selected=list(GENERATORS) if args.all or not args.runtime else args.runtime
    files=expected(selected)
    if args.check:
        bad=check_files(files)
        if bad:
            print('RAD adapter drift detected:')
            for b in bad: print(' -',b)
            return 1
        print(f'RAD adapters in sync (core {CORE_HASH}): '+', '.join(selected))
        return 0
    write_files(files)
    print(f'Generated RAD adapters (core {CORE_HASH}): '+', '.join(selected))
    return 0

if __name__=='__main__': sys.exit(main())
